// Code generated by pgxgen. DO NOT EDIT.
// versions:
//   pgxgen v0.2.6

package users

type TableName string

func (s TableName) String() string {
	return string(s)
}

const (
	TableNameUsers TableName = "users"
)
