// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package users

import (
	"context"
	. "tokeon-test-task/internal/models"

	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*User, error)
	Get(ctx context.Context, id uuid.UUID) (*User, error)
	Update(ctx context.Context, arg UpdateParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
